name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup CML
      - uses: iterative/setup-cml@v2
        with:
          version: latest
          vega: true

      # Step 3: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # or your desired Python version

      # Step 4: Upgrade pip and install dependencies
      - name: Install Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.
